//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
//
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the
//   distribution.
//
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "switch_PinMux.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"

#define B_LED 0x04
#define R_LED 0x02
#define SW1 GPIO_PIN_4
#define SW2 GPIO_PIN_0
//*****************************************************************************
void PortFunctionInit(void)
{
  //
  // Enable Peripheral Clocks
  //
  SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

  //
  // Enable pin PF2 for GPIOOutput
  //
  GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, B_LED | R_LED);

  //
  // Enable pin PF0 for GPIOInput
  //

  //
  // First open the lock and select the bits we want to modify in the GPIO commit register.
  //
  HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
  HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

  //
  // Now modify the configuration of the pins that we unlocked.
  //
  GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, SW1 | SW2);

  //
  // Enable pin PF1 for GPIOOutput
  //

  GPIO_PORTF_PUR_R |= 0x11; // Enable pull-up on PF0 (sw1) and PF4 (sw2)
}

int main(void)
{
  PortFunctionInit();                // initialize the GPIO ports
  int freq = 100;                    // variable to adjust frequency that lights flash at
  int delay = 16000000 / (3 * freq); // delay used for switch checking, roughly 0.01 seconds
  int target_led = R_LED | B_LED;    // sets initial condition for variable to purple. this is for error checking.
  uint8_t LED_data = 0;              // 8 bit unsigned variable
  for (;;)
  {                   // loops forever
    LED_data ^= 0xff; // toggle before going into loop
    for (int i = 0; i < freq / 2; i++)
    { //  for loop to iterate every half second
      int sw1 = GPIOPinRead(GPIO_PORTF_BASE, SW1);
      int sw2 = GPIOPinRead(GPIO_PORTF_BASE, SW2);
      if (!sw2 && !sw1)
      {
        GPIOPinWrite(GPIO_PORTF_BASE, R_LED | B_LED, 0x00); // sets to the red and blue LED to off
      }
      else if (!sw1 && sw2)
      {
        GPIOPinWrite(GPIO_PORTF_BASE, R_LED | B_LED, LED_data & R_LED); // when switch 1 is pressed, the red LED light is on
      }
      else if (sw1 && !sw2) // when switch 2 is pressed
      {
        GPIOPinWrite(GPIO_PORTF_BASE, R_LED | B_LED, 0x00);
      }
      else if (sw1 && sw2)
      {
        GPIOPinWrite(GPIO_PORTF_BASE, R_LED | B_LED, LED_data & B_LED);
      }

      SysCtlDelay(delay); // Delay for 1/freq seconds.
    }
  }
}
